/*
 HTML5 3D Flipping Gallery
 Version: 1.0.2
 (c) 2013 DMXzone.com
 @build 06-02-2013 10:37:09
*/
(function(c){function i(b){for(var c=document.createElement("div").style,d=["","-webkit","-moz","-o","-ms"],h=["","Webkit","Moz","O","ms"],o=0;o<h.length;o++)if(h[o]+b in c)return d[o]+b.replace(/([A-Z])/g,"-$1").toLowerCase();return!1}var N={animationDuration:400,rotation:"random",maxRotation:10,random:!1,shuffle:!1,shufflePlacement:"uniform",zoomTrigger:"hover",zoomFactor:1.2,flipTrigger:"click",flipEffect:"default",flipDirection:"left",flipRotation:0,singleActive:!0,perspective:800},H="dmx3DFlipGallery",
s="dmx3DFlipPhoto",t="dmx3DFlipPhotoActive",I="dmx3DFlipPhotoWrapper",O="dmx3DFlipPhotoFront",q="dmx3DFlipPhotoBack",w="dmx3DFlipPhotoFlipped",u=i("Transition"),d=i("Transform"),P=i("TransformOrigin"),J=i("Perspective"),x=i("TransformStyle"),Q=i("BackfaceVisibility"),l=!1!==J,h=!0==l;c(function(){if(l&&"webkitPerspective"in c("body").get(0).style){var b=c('<div id="csstransform3d"></div>'),d=c('<style media="(transform-3d),(-webkit-transform-3d)">div#csstransform3d{position:absolute;left:9px;height:3px;}</style>');
c("body").append(b);c("head").append(d);l=9===b[0].offsetLeft&&3===b[0].offsetHeight;b.remove();d.remove()}h&&(b=c('<div style="'+x+': preserve-3d;"></div>'),c("body").append(b),h="preserve-3d"==b.css(x).toLowerCase(),b.remove())});c.fn.dmx3DFlipGallery=function(b){function f(c){var d=c.data("translate")||[0,0],f=c.data("scale")||1,n=c.data("rotateX")||0,m=c.data("rotateY")||0,c=c.data("rotateZ")||c.data("rotate")||0;/^\d+$/.test(d[0])&&(d[0]+="px");/^\d+$/.test(d[1])&&(d[1]+="px");return l?(h?"":
"perspective("+b.perspective+"px) ")+"translate3D("+d[0]+","+d[1]+",0px) scale("+f+") rotateX("+n+"deg) rotateY("+m+"deg) rotateZ("+c+"deg)":"translate("+d[0]+"px,"+d[1]+"px) scale("+f+") rotate("+c+"deg)"}var b=c.extend({},N,b),n=Math.random,m=Math.floor;return this.each(function(){function o(){var a=!0;g.find("img").each(function(){if(0==this.width||0==this.height)a=!1});a?(g.find("img").mousedown(function(c){c.preventDefault()}),l?(/^top|bottom$/i.test(b.flipDirection)?c("."+q).data("rotateX",
180):c("."+q).data("rotateY",180),c("."+q).each(function(){c(this).css(d,f(c(this).parent())+" "+f(c(this)))}),c("."+O).css(d,f(c(this).parent())+" "+f(c(this)))):c("."+q).hide(),k.each(function(a){var j=c(this),i=j.width(),k=j.height(),e=j.wrap('<div class="'+I+'" />').parent();if(l){if(h){e.css(J,b.perspective+"px");j.css(x,"preserve-3d")}j.children().css(Q,"hidden");if(b.flipEffect=="slide"&&h){var g="center center";switch(b.flipDirection){case "top":g="center top";break;case "left":g="left center";
break;case "bottom":g="center bottom";break;case "right":g="right center"}j.css(P,g)}}j.data("rotation",j.data("rotation")||b.rotation);j.data("rotation")=="random"&&j.data("rotation",m(n()*(b.maxRotation*2+1))-b.maxRotation);d&&e.data("rotate",parseInt(j.data("rotation")));if(b.shuffle){e.css("position","absolute");switch(b.shufflePlacement){case "jittered":i=a%r;a=m(a/r);i=m(i*A+n()*(A/2)+A/4);a=m(a*B+n()*(B/2)+B/4);e.css({left:i,top:a});break;default:e.css({left:m(n()*(C-i)),top:m(n()*(D-k))})}}else e.css({position:"relative",
display:"inline-block"});if(d){e.css(d,f(e));j.css(d,f(j))}}),u&&(k.css(u,d+" "+b.animationDuration+"ms").parent().css(u,d+" "+b.animationDuration+"ms"),l&&!h&&k.children().css(u,d+" "+b.animationDuration+"ms")),b.random&&(k.shuffle(),k=g.find("."+s)),g.on("fakeclick","."+s,function(){var a=c(this);if(b.zoomTrigger=="click"){d&&(a.data("scale")==1?K(a):y(a));b.singleActive&&y(k.not(a).filter("."+t))}if(b.flipTrigger=="click"){a.hasClass(w)?z(a):L(a);b.singleActive&&z(k.not(a).filter("."+t))}b.singleActive&&
k.not(a).filter("."+t).removeClass(t);a.addClass(t)}).on("mouseenter","."+s,function(){var a=c(this);b.zoomTrigger=="hover"&&K(a);b.flipTrigger=="hover"&&L(a)}).on("mouseleave","."+s,function(){var a=c(this);b.zoomTrigger=="hover"&&y(a);b.flipTrigger=="hover"&&z(a)}).on("mousedown touchstart","."+I,function(a){if(a.type=="touchstart"){a.preventDefault();a=a.originalEvent.touches[0]}var d=c(this),f=false,e=d.position(),h=a.pageX-e.left,g=a.pageY-e.top;i(d);if(b.shuffle)c("body").on("mousemove.dmx3DFlipGallery touchmove.dmx3DFlipGallery",
function(a){a.type=="touchmove"&&(a=a.originalEvent.touches[0]);f=true;d.css({left:a.pageX-h,top:a.pageY-g})});c("body").on("mouseup.dmx3DFlipGallery touchend.dmx3DFlipGallery",function(a){c("body").off(".dmx3DFlipGallery");if(!f){if(a.type=="touchend"&&a.srcElement){var b=a.originalEvent,e=document.createEvent("MouseEvents");e.initMouseEvent("click",true,true,b.view,1,b.changedTouches?b.changedTouches[0].screenX:b.screenX,b.changedTouches?b.changedTouches[0].screenY:b.screenY,b.changedTouches?b.changedTouches[0].clientX:
b.clientX,b.changedTouches?b.changedTouches[0].clientY:b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null);a.srcElement.dispatchEvent(e)}d.children().trigger("fakeclick")}})}),g.removeClass(H+"Loading")):setTimeout(o,100)}function i(a){var b,d=parseInt(a.css("z-index"))||0;a.siblings().each(function(){b=parseInt(c(this).css("z-index"))||0;d<=b&&(d=b+1)});a.css("z-index",d)}function K(a){d&&(a.data("scale",b.zoomFactor),l&&!h?a.children().each(function(){c(this).css(d,f(a)+" "+f(c(this)))}):
a.css(d,f(a)));i(a.parent())}function y(a){d&&(a.data("scale",1),l&&!h?a.children().each(function(){c(this).css(d,f(a)+" "+f(c(this)))}):a.css(d,f(a)))}function z(a){var e=a.parent();a.removeClass(w);d&&e.data("rotate",a.data("rotation")).css(d,f(e));l?("slide"==b.flipEffect&&h&&a.data("translate",[0,0]),/^top|bottom$/i.test(b.flipDirection)?a.data("rotateX",0):a.data("rotateY",0),h?a.css(d,f(a)):a.children().each(function(){c(this).css(d,f(a)+" "+f(c(this)))})):a.find("."+q).hide()}function L(a){var e=
a.parent();a.addClass(w);d&&("random"==b.flipRotation?e.data("rotate",m(n()*(2*b.maxRotation+1))-b.maxRotation).css(d,f(e)):"none"!=b.flipRotation&&e.data("rotate",parseInt(b.flipRotation)).css(d,f(e)));if(l){var g=/^top|left$/i.test(b.flipDirection)?-180:180;if("slide"==b.flipEffect&&h)switch(b.flipDirection){case "top":a.data("translate",[0,"100%"]);break;case "left":a.data("translate",["100%",0]);break;case "bottom":a.data("translate",[0,"-100%"]);break;case "right":a.data("translate",["-100%",
0])}/^top|bottom$/i.test(b.flipDirection)?a.data("rotateX",g):a.data("rotateY",g);h?a.css(d,f(a)):a.children().each(function(){c(this).css(d,f(a)+" "+f(c(this)))})}else a.find("."+q).show();i(e)}var g=c(this),k=g.find("."+s),C=g.width(),D=g.height(),v=k.length,r=v,e=1,E=0,F=0;if("jittered"==b.shufflePlacement){var p=1,M=0;for(k.each(function(){var a=c(this).width(),b=c(this).height();E=Math.max(E,a);F=Math.max(F,b);p+=a/b;p/=2});e<v;){var G=C/r/(D/e);if(G>p){if(1==e)break;Math.abs(p-G)>Math.abs(p-
M)&&(e-=1,r=Math.ceil(v/e));break}M=G;e+=1;r=Math.ceil(v/e)}}var A=(C-E)/r,B=(D-F)/e;g.addClass(H+"Loading");o()})};c.fn.shuffle=function(){var b=this.get(),d=c.map(b,function(){var d=Math.floor(Math.random()*b.length),f=c(b[d]).clone(!0)[0];b.splice(d,1);return f});this.each(function(b){c(this).replaceWith(c(d[b]))});return c(d)}})(window.jQuery||window.Zepto);